name: Evolution X Build System

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: udc

      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3

      - name: Install Google Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Initialize and Sync
        run: |
          git config --global user.email "ali@example.com"
          git config --global user.name "Ali"
          mkdir -p build && cd build
          
          # Repo'yu başlat
          repo init -u https://github.com/Evolution-X/manifest -b udc --depth=1 --no-repo-verify
          
          # Local manifest'i kopyala
          mkdir -p .repo/local_manifests
          cp ../local_manifests/noble.xml .repo/local_manifests/
          
          # HATA ÖNLEYİCİ: 'github' remote tanımını temizle
          cd .repo/manifests
          git remote remove github || true
          cd ../..
          
          # Zorunlu senkronizasyon
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune --force-remove-dirty

      - name: Start ROM Cooking
        run: |
          cd build
          source build/envsetup.sh
          lunch evolution_noblelte-userdebug
          mka bacon -j$(nproc --all)

      - name: Upload Finished ROM
        uses: actions/upload-artifact@v4
        with:
          name: EvolutionX-Note5-Build
          path: build/out/target/product/noblelte/*.zip
